module.exports = {
    FabricaModel : require('./includes/fabricaModel'),
    ProdutoModel : require('./includes/produtoModel'),
    GrupoModel : require('./includes/grupoModel'),
    VolumeModel : require('./includes/volumeModel'),
    TipoUnidadeModel: require('./includes/tipoUnidadeModel'),
    ClienteModel: require('./includes/clienteModel'),
    EstadoModel: require('./includes/estadoModel'),
    MunicipioModel: require('./includes/municipioModel'),
    EnderecoModel: require('./includes/enderecoModel'),
    UsuarioModel: require('./includes/usuarioModel'),
    NotaEntradaModel : require('./includes/notaEntradaModel'),
    ItemNotaEntradaModel : require('./includes/itemEntradaNotaModel'),
    MovimentacaoModel: require('./includes/movimentacaoModel'),
    PedidoClienteModel: require('./includes/pedidoClienteModel'),
    ItemPedidoClienteModel: require('./includes/itemPedidoClienteModel'),
    RecebimentoModel: require('./includes/recebimentoModel'),
    HistoricoRecebimentoModel: require('./includes/historicoRecebimentoModel'),
    FormaPagamentoModel: require('./includes/formaPagamentoModel'),
    InventarioModel : require('./includes/InventarioModel'),
    DespesaModel : require('./includes/despesaModel'),
    HistoricoDespesaModel : require('./includes/historicoDespesaModel'),
    VendedorModel: require('./includes/vendedorModel'),
    TelefoneModel : require('./includes/telefoneModel'),
    ProdutoEcommerceModel : require('./includes/ProdutoEcommerceModel'),
    GrupoEcommerceModel : require('./includes/grupoEcommerceModel'),
    PedidoFabricaModel : require('./includes/pedidoFabricaModel'),
    ItemPedidoFabricaModel: require('./includes/itemPedidoFabricaModel'),
    BancoModel: require('./includes/bancoModel'),
    AgenciaModel: require('./includes/agenciaModel'),
    ContaBancariaModel: require('./includes/contaBancariaModel'),
    CedenteModel: require('./includes/cedenteModel'),
    ChequeModel : require('./includes/chequeModel'),
    HistoricoChequeModel : require('./includes/historicoChequeModel'),
    PessoaModel: require('./includes/pessoaModel'),
    MotivoDevolucaoChequeModel : require('./includes/motivoDevolucaoChequeModel')    
    

}