module.exports = {
    JqueryUtil : require('./_utils/jquery-util')(),
    NumberUtil : require('./_utils/number-util')(),
    DateUtil : require('./_utils/date-util')(),
    MobileUtil : require('./_utils/mobile-util')(),
    ObjectUtil : require('./_utils/object-util')(),
    ModalUtil : require('./_utils/modal-util')(),
    MessageUtil : require('./_utils/message-util')(),
    UrlUtil : require('./_utils/url-util')(),
    HtmlUtil: require('./_utils/html-util')(),
    BreadCrumb: require('./_utils/breadcrumb-util')(),
    FormUtil: require('./_utils/form-util')(),
    JsonUtil: require('./_utils/json-util')(),
    UnderscoreUtil: require('./_utils/underscore-utils')(),
    ApiUtil: require('./_utils/api-utils')(),
    EstadoMunicipioUtil : require('./_utils/estado-municipio-util')(),
    MaskInputUtil : require('./_utils/mask-input-util')(),
    AutoCompleteUtil : require('./_utils/auto-complete-util'),
    localStorageUtil : require('./_utils/local-storage-util'),
    ServiceWorkerUtil : require('./_utils/service-worker-utils'),
    BackboneModelUtil : require('./_utils/backbone-model-admin-utils'),
    StringUtil: require('./_utils/string-util')(),
    IndexedDbUtil: require('./_utils/indexed-db-utils')(),
    SincronizacaoServiceUtil : require('./_utils/sincronizacao-service-util')(),
    JQXTreeUtil :  require('./_utils/jquery-util')(),
    PaginatorUtil: require('./_utils/paginator-util')(),
    TelefoneUtil: require('./_utils/telefone-utils'),
    LocationUtil: require('./_utils/location-util'),
    PromiseUtil: require('./_utils/promise-util'),
    SessionStorageUtil: require('./_utils/session-storage-util'),
    TableUtil: require('./_utils/list-components/table-utils'),
    EventUtil: require('./_utils/event-utils')
}